$(function(){
	$("#content").load("./pages/shouye.html")
	$('#nav').on({
	click:function(){
		// console.log($(this).text())
		if($(this).text()=='首页'){
	        $('#content').load('./pages/shouye.html');
			}
		if($(this).text()=='商家管理'){
	        $('#content').load('./pages/bussiness.html');
			}
		if($(this).text()=='招聘管理'){
	        $('#content').load('./pages/zhaoping.html');
			}
		if($(this).text()=='用户管理'){
	        $('#content').load('./pages/custemer.html');
			}
		if($(this).text()=='模块管理'){
	        $('#content').load('./pages/mokuai.html');
			}
		if($(this).text()=='求职联系'){
	        $('#content').load('./pages/apply.html');
			}
		if($(this).text()=='客服管理'){
	        $('#content').load('./pages/service.html');
			}
		if($(this).text()=='审核模块'){
	        $('#content').load('./pages/check.html');
			}

	}
	},'span')
})